# Generated by Django 4.2.13 on 2024-08-03 06:12

from django.db import migrations, models
import tags.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, validators=[tags.validators.validate_gender])),
                ('disease', models.CharField(max_length=100, null=True)),
                ('recommended_medicine', models.CharField(max_length=200, null=True)),
                ('qr_code', models.TextField(blank=True)),
                ('subscription_id', models.CharField(max_length=200, unique=True)),
                ('delivery_address', models.CharField(max_length=200)),
                ('subscription_choice', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lifetime', 'Lifetime')], default='Monthly', max_length=8, validators=[tags.validators.validate_subscription_choice])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
