# Generated by Django 4.2.13 on 2024-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='qr_code',
            field=models.TextField(blank=True),
        ),
    ]
