# Generated by Django 4.2.13 on 2024-07-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
