# Generated by Django 4.2.13 on 2024-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_alter_tag_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='delivery_address',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='subscription_choice',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lifetime', 'Lifetime')], default='Monthly', max_length=8),
        ),
        migrations.AddField(
            model_name='tag',
            name='subscription_id',
            field=models.CharField(default=999, max_length=200),
            preserve_default=False,
        ),
    ]
