# Generated by Django 4.2.13 on 2024-07-02 14:10

from django.db import migrations, models
import tags.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_tag_delivery_address_tag_subscription_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, validators=[tags.validators.validate_gender]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subscription_choice',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Lifetime', 'Lifetime')], default='Monthly', max_length=8, validators=[tags.validators.validate_subscription_choice]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subscription_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
